config/routes.rb
Rails.application.routes.draw do
  resources :personas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :welcomes
	root 'welcomes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/persona.rb
class Persona < ApplicationRecord
end

app/models/welcome.rb
class Welcome < ApplicationRecord

	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:name, :description, :age, :birthday, :nickname)
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController	

	before_action :set_welcome, only:[:show,:edit,:update,:destroy]

	def new
		@welcome = Welcome.new
	end

	def index
		@welcome = Welcome.all()
	end

	def show

  end

	def create
		@welcome = Welcome.new(welcome_params)
  	@welcome.save
  	redirect_to @welcome
	end

	def destroy
		@welcome.destroy
		redirect_to '/'
	end

	def edit
		
	end

	def update
		@welcome.update(welcome_params)
	end

	private 
		def welcome_params
    	params.require(:welcome).permit(:title, :text)
  	end
		
		def set_welcome
			@welcome = Welcome.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/personas/_form.html.erb
<%= form_with(model: persona, local: true) do |form| %>
  <% if persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :persona_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :persona_description %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :persona_age %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, id: :persona_birthday %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, id: :persona_nickname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Age</th>
      <th>Birthday</th>
      <th>Nickname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.name %></td>
        <td><%= persona.description %></td>
        <td><%= persona.age %></td>
        <td><%= persona.birthday %></td>
        <td><%= persona.nickname %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @persona.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @persona.description %>
</p>

<p>
  <strong>Age:</strong>
  <%= @persona.age %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @persona.birthday %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @persona.nickname %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>

app/views/welcomes/edit.html.erb
<html>
	<head>
		<style type="text/css">
			*{
				margin: 0;
				padding: 0;
				font-family: sans-serif;			
			}
		</style>	
	</head>
	<body>
		<header>Welcome to my world!</header>
		<%= form_with(model:@welcome) do |f| %>
 			<p>
    				<%= f.label :title %><br>
    				<%= f.text_field :title %>
  			</p>
 		
 			<p>
    				<%= f.label :text %><br>
    				<%= f.text_area :text %>
  			</p>
 
  			<p>
    				<%= f.submit %>
  			</p>
		<% end %>
		
	</body>
</html>

app/views/welcomes/index.html.erb
<html>
	<head>
		<style type="text/css">
			*{
				margin: 0;
				padding: 0;
				font-family: sans-serif;
			}
			header{
				font-size: 40px;
				background: rgb(225,10,10);
				color: white;
				line-height: 50px;
				padding: 10px;
				margin-bottom: 10px;
			}

			table tr td,th{
				width: 250px;
				border: 1px solid black;
				margin: 10px;
				padding: 10px;
			}

			table tr .id_column{
				width: 50px;
				text-align: center;
			}

			table tr td.link{
				width: 50px;	
				text-align: center;
			}

			a{
				font-style: none;
				color: rgb(200,100,0)			
			}


		</style>
	</head>
	<body>
		<header>
			Welcome to Ruby on Rails!
		</header>

		<table>
			<tr>
				<th class="id_column">ID</th>
				<th>Title</th>
				<th>Text</th>
			</tr>
			<% @welcome.each do |disp| %>
			<tr>
				<td class="id_column"><%= disp.id%></td>
				<td><%= disp.title%></td>
				<td><%= disp.text%></td>
				<td class="link"><%=link_to 'Show', disp%></td>
				<td class="link"><%=link_to 'Edit', edit_welcome_path(disp)%></td>
				<td class="link"><%=link_to 'Destroy', disp, method: :delete, data:{confirm: 'Are you sure?'}%></td>
			</tr>
			<%end%>
		</table>
		<%=link_to 'New', new_welcome_path%>

	</body>
</html>

app/views/welcomes/new.html.erb
<html>
	<head>
		<style type="text/css">
			*{
				margin: 0;
				padding: 0;
				font-family: sans-serif;			
			}
		</style>	
	</head>
	<body>
		<header>Welcome to my world!</header>
		<%= form_with(model:@welcome) do |f| %>
 			<p>
    				<%= f.label :title %><br>
    				<%= f.text_field :title %>
  			</p>
 		
 			<p>
    				<%= f.label :text %><br>
    				<%= f.text_area :text %>
  			</p>
 
  			<p>
    				<%= f.submit %>
  			</p>
		<% end %>
		
	</body>
</html>

app/views/welcomes/show.html.erb
<html>
	<head>
		<style type="text/css">
			*{
				margin: 0px;
				padding: 0px;
				font-family: sans-serif
			}
			header{
				font-size: 40px;
				background: rgb(225,10,10);
				color: white;
				line-height: 50px;
				padding: 10px;
				margin-bottom: 10px;
			}
			h3{
				margin: 10px;
			}
			p{
				margin: 10px;			
			}
		</style>	
	</head>
	<body>
		<header>Show</header>		
		<h3><%=@welcome.title%></h3>
		<hr />		
		<p><%=@welcome.text%></p>
	</body>
</html>